apiVersion: apps/v1
kind: Deployment
metadata:
  name: delivery-service
  labels:
    app: delivery-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: delivery-service
  template:
    metadata:
      labels:
        app: delivery-service
    spec:
      containers:
        - name: delivery-service
          image: eatr/delivery-service:latest
          ports:
            - containerPort: 3005
          env:
            - name: NODE_ENV
              value: "production"
            - name: PORT
              value: "3005"
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: eatr-config
                  key: db_host
            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: eatr-config
                  key: db_port
            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: eatr-config
                  key: db_name
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: eatr-secrets
                  key: db_user
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: eatr-secrets
                  key: db_password
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: eatr-secrets
                  key: jwt_secret
            - name: GOOGLE_MAPS_API_KEY
              valueFrom:
                secretKeyRef:
                  name: eatr-secrets
                  key: google_maps_api_key
            - name: KAFKA_BROKERS
              valueFrom:
                configMapKeyRef:
                  name: eatr-config
                  key: kafka_brokers
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
          livenessProbe:
            httpGet:
              path: /health
              port: 3005
            initialDelaySeconds: 15
            periodSeconds: 20
          readinessProbe:
            httpGet:
              path: /health
              port: 3005
            initialDelaySeconds: 5
            periodSeconds: 10

---
apiVersion: v1
kind: Service
metadata:
  name: delivery-service
spec:
  selector:
    app: delivery-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3005
  type: ClusterIP
