apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-service
  labels:
    app: notification-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: notification-service
  template:
    metadata:
      labels:
        app: notification-service
    spec:
      containers:
        - name: notification-service
          image: eatr/notification-service:latest
          ports:
            - containerPort: 3006
          env:
            - name: NODE_ENV
              value: "production"
            - name: PORT
              value: "3006"
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: eatr-config
                  key: db_host
            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: eatr-config
                  key: db_port
            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: eatr-config
                  key: db_name
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: eatr-secrets
                  key: db_user
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: eatr-secrets
                  key: db_password
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: eatr-secrets
                  key: jwt_secret
            - name: KAFKA_BROKERS
              valueFrom:
                configMapKeyRef:
                  name: eatr-config
                  key: kafka_brokers
            - name: SMTP_HOST
              valueFrom:
                configMapKeyRef:
                  name: eatr-config
                  key: smtp_host
            - name: SMTP_PORT
              valueFrom:
                configMapKeyRef:
                  name: eatr-config
                  key: smtp_port
            - name: SMTP_USER
              valueFrom:
                secretKeyRef:
                  name: eatr-secrets
                  key: smtp_user
            - name: SMTP_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: eatr-secrets
                  key: smtp_password
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
          livenessProbe:
            httpGet:
              path: /health
              port: 3006
            initialDelaySeconds: 15
            periodSeconds: 20
          readinessProbe:
            httpGet:
              path: /health
              port: 3006
            initialDelaySeconds: 5
            periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: notification-service
spec:
  selector:
    app: notification-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3006
  type: ClusterIP
